### ISSUE TITLE
Cannot enable addon on Windows 10

### ISSUE THREAD

**Issue by dreisicht** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#108]
I downloaded `BlenderUSDHydraAddon_1.0.21_Windows.zip`, installed with the Blender add-on UI, and I get the following error:
```
2021-09-22 10:57:11,539 INFO hdusd.init [16336]:  Loading USD Hydra addon version=(1, 0, 21), build=b0bf57e
Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\peter\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\__init__.py", line 39, in <module>
    from . import engine, properties, ui, usd_nodes, mx_nodes, bl_nodes
  File "C:\Users\peter\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\engine\__init__.py", line 39, in <module>
    from . import engine, handlers
  File "C:\Users\peter\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\engine\engine.py", line 20, in <module>
    from pxr import UsdGeom
  File "C:\Users\peter\Documents\pixar\lib\python\pxr\UsdGeom\__init__.py", line 24, in <module>
    from . import _usdGeom
ImportError: DLL load failed while importing _usdGeom: Das angegebene Modul wurde nicht gefunden.
```

**Comment by bsavery** [comment]
What blender version is this?

**Comment by dreisicht** [comment]
It's 2.93.4!

**Comment by bnagirniak** [comment]
Looks like `from pxr import UsdGeom` tries to load pxr library from C:\Users\peter\Documents\pixar\lib\python\pxr. Addon has its own pxr library inside C:\Users\peter\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\libs\usd\python\pxr, such library should be used.
Try to remove C:\Users\peter\Documents\pixar\lib\python from PYTHONPATH if it is there.

**Comment by dreisicht** [comment]
Looks like that resolved one issue. Now I run into the following one:
```
2021-09-29 14:28:01,949 INFO hdusd.init [20824]:  Loading USD Hydra addon version=(1, 0, 21), build=b0bf57e
Fatal Python error: take_gil: NULL tstate
```
I think my python installation is a bit off, so feel free to close the ticket in case you don't want to invest time into debugging this.

**Comment by bnagirniak** [comment]
Not actual anymore.
