### ISSUE TITLE
Adding renderers to USD Hydra plugin for Blender

### ISSUE THREAD

**Issue by bsavery** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#111]
### Discussed in https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon/discussions/109

<div type='discussions-op-text'>

<sup>Originally posted by **KY-Hage** September 25, 2021</sup>
Hi there,

I'm a bit confused about how to add Renderman or any other USD render delegate as renderers in the [USD Hydra plugin for Blender](https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#installing-add-on). In the readme it states that I could add compatible renderers in my libs/plugins/usd folder. My issue is I'm unsure if I am compiling this correctly.

I'm using Blender 2.93.1

After following the instruction on [Pixar's Github](https://github.com/PixarAnimationStudios/USD) I successfully used the build_usd.py script with the additional options for Renderman by using

`py -m build_usd --prman --prman-location "C:\Program Files\Pixar\RenderManProServer-24.1" "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\libs\plugins\usd"`

This gave me an error dealing with the installation of Boost. I was able to get around that by change the filepath to  `"C:\Users\User\AppData\Roaming\BlenderFoundation\Blender\2.93\scripts\addons\hdusd\libs"`  since the space in the folder name caused the issue.

I then had this error appear when I tried to enable the addon in Blender:
```
Traceback (most recent call last):
  _File "D:\Blender\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\__init__.py", line 39, in <module>
    from . import engine, properties, ui, usd_nodes, mx_nodes, bl_nodes
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\engine\__init__.py", line 39, in <module>
    from . import engine, handlers
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\engine\engine.py", line 42, in <module>
    from . import final_engine, viewport_engine, preview_engine
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\engine\final_engine.py", line 19, in <module>
    from pxr import UsdImagingGL, UsdImagingLite
ImportError: cannot import name 'UsdImagingLite' from 'pxr' (C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\libs\lib\python\pxr\__init__.py)_

```

Some other points:
1. When reading through the [advanced build configuration](https://github.com/PixarAnimationStudios/USD/blob/release/BUILDING.md#advanced-build-configuration) I noticed multiple times it said I would need to supply the location of the additional dependencies. I only did this for Renderman and I followed the format [shown here](https://graphics.pixar.com/usd/docs/RenderMan-USD-Imaging-Plugin.html) by adding the location argument in the command line.

2. I'm unsure which folder I'm supposed to be compiling to as I noticed my file paths had \libs\usd\lib\usd and the plugin didn't work and the times I tried reinstalling it on different levels of the filepath also failed.

Questions:
Are the [other renderers](https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#blender-usd-hydra-addon) not actually usable with the blender addon yet? Did I compile the Renderman delegate or any of the other options correctly? If so where are they and is there any more configuration needed to get the to work?

I apologize if my questions seem really basic as I'm not a developer. I'm just a 3D artist who thought it would be cool to use this. Now after spending over 14 hours on trying to get this to work I am running out of ideas.

Hopefully someone has some experience with this situation and can lend a hand.

Thanks a ton!</div>

**Comment by DagerD** [comment]
Renderman will be added with this https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon/pull/234

**Comment by bsavery** [comment]
Closed because RenderMan is added!
