### ISSUE TITLE
Fail rendering Bistro scene

### ISSUE THREAD

**Issue by smeunier-amd** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#162]
Here's the scene :
https://developer.nvidia.com/orca/amazon-lumberyard-bistro

Package :
BlenderUSDHydraAddon_1.0.55_Windows.(PR-159).zip

Blender :
2.93.1

Steps :
Install and enable BlenderUSDHydraAddon_1.0.55_Windows.(PR-159).zip;
Restart Blender (or not);
Import Bistro_v5_2\BistroExterior.fbx;
Enable Full or HybridPro renderer through USD Hydra;
Activate Camera.001 and pick any frame;
Press F12 (Render);
Toggle System Console and see the following warnings and errors.

```
Read prefs: C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\config\userpref.blend
2021-12-01 16:59:11,493 INFO hdusd.init [15860]:  Loading USD Hydra addon version=(1, 0, 55), build=90cfad1
Info: Deleted 2 object(s)

FBX Import: start importing C:\Users\AMD\Downloads\Bistro_v5_2\BistroExterior.fbx
FBX version: 7500
        FBX import: Prepare...
                Done (0.000000 sec)

        FBX import: Templates...
                Done (0.000000 sec)

        FBX import: Nodes...
                Done (0.015625 sec)

        FBX import: Connections...
                Done (0.015625 sec)

        FBX import: Meshes...
                Done (69.687500 sec)

        FBX import: Materials & Textures...
                Done (8.906250 sec)

        FBX import: Cameras & Lamps...
                Done (0.000000 sec)

        FBX import: Objects & Armatures...
                Done (0.343750 sec)

        FBX import: ShapeKeys...
                Done (0.000000 sec)

        FBX import: Animations...
                Done (0.062500 sec)

        FBX import: Assign materials...
                Done (0.078125 sec)

        FBX import: Assign textures...
                Done (6.875000 sec)

        FBX import: Cycles z-offset workaround...
                Done (0.000000 sec)

        Done (88.171875 sec)

Import finished.
WARN (bpy.rna): C:\Users\blender\git\blender-v293\blender.git\source\blender\python\intern\bpy_rna.c:1505 pyrna_enum_to_py: current value '29' matches no enum in 'Image', 'Stringlights_BaseColor', 'file_format'
2021-12-01 17:01:23,393 ERROR hdusd.engine [15860]:  bpy_struct: item.attr = val: enum "" not found in ('BMP', 'IRIS', 'PNG', 'JPEG', 'JPEG2000', 'TARGA', 'TARGA_RAW', 'CINEON', 'DPX', 'OPEN_EXR_MULTILAYER', 'OPEN_EXR', 'HDR', 'TIFF', 'AVI_JPEG', 'AVI_RAW', 'FFMPEG'), EXCEPTION:, Traceback (most recent call last):
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\engine\engine.py", line 107, in view_update
    self.engine.sync(context, depsgraph)
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\engine\viewport_engine.py", line 195, in sync
    self._sync(context, depsgraph)
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\engine\viewport_engine.py", line 372, in _sync
    object.sync(root_prim, obj_data)
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\export\object.py", line 127, in sync
    mesh.sync(obj_prim, obj, **kwargs)
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\export\mesh.py", line 261, in sync
    _assign_materials(obj_prim, obj.original, usd_mesh)
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\export\mesh.py", line 267, in _assign_materials
    usd_mat = material.sync(obj_prim, obj.material_slots[0].material, obj)
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\export\material.py", line 41, in sync
    doc = mat.hdusd.export(obj)
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\properties\material.py", line 58, in export
    if not node_parser.export():
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\bl_nodes\nodes\output.py", line 25, in export
    surface = self.get_input_link('Surface')
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\bl_nodes\node_parser.py", line 351, in get_input_link
    return self._export_node(link.from_node, link.from_socket.identifier)
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\bl_nodes\node_parser.py", line 294, in _export_node
    node_item = node_parser.export()
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\bl_nodes\nodes\shader.py", line 46, in export
    base_color = self.get_input_value('Base Color')
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\bl_nodes\node_parser.py", line 356, in get_input_value
    val = self.get_input_link(in_key)
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\bl_nodes\node_parser.py", line 351, in get_input_link
    return self._export_node(link.from_node, link.from_socket.identifier)
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\bl_nodes\node_parser.py", line 294, in _export_node
    node_item = node_parser.export()
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\bl_nodes\nodes\texture.py", line 31, in export
    img_path = cache_image_file(image)
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\utils\image.py", line 54, in cache_image_file
    image.file_format = old_file_format
TypeError: bpy_struct: item.attr = val: enum "" not found in ('BMP', 'IRIS', 'PNG', 'JPEG', 'JPEG2000', 'TARGA', 'TARGA_RAW', 'CINEON', 'DPX', 'OPEN_EXR_MULTILAYER', 'OPEN_EXR', 'HDR', 'TIFF', 'AVI_JPEG', 'AVI_RAW', 'FFMPEG')

WARN (bpy.rna): C:\Users\blender\git\blender-v293\blender.git\source\blender\python\intern\bpy_rna.c:1505 pyrna_enum_to_py: current value '29' matches no enum in 'Image', 'Stringlights_Specular', 'file_format'
2021-12-01 17:04:16,161 ERROR hdusd.engine [19464]:  bpy_struct: item.attr = val: enum "" not found in ('BMP', 'IRIS', 'PNG', 'JPEG', 'JPEG2000', 'TARGA', 'TARGA_RAW', 'CINEON', 'DPX', 'OPEN_EXR_MULTILAYER', 'OPEN_EXR', 'HDR', 'TIFF', 'AVI_JPEG', 'AVI_RAW', 'FFMPEG'), EXCEPTION:, Traceback (most recent call last):
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\engine\engine.py", line 75, in update
    self.engine.sync(depsgraph)
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\engine\final_engine.py", line 187, in sync
    self._sync(depsgraph)
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\engine\final_engine.py", line 281, in _sync
    object.sync(root_prim, obj_data)
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\export\object.py", line 127, in sync
    mesh.sync(obj_prim, obj, **kwargs)
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\export\mesh.py", line 261, in sync
    _assign_materials(obj_prim, obj.original, usd_mesh)
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\export\mesh.py", line 267, in _assign_materials
    usd_mat = material.sync(obj_prim, obj.material_slots[0].material, obj)
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\export\material.py", line 41, in sync
    doc = mat.hdusd.export(obj)
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\properties\material.py", line 58, in export
    if not node_parser.export():
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\bl_nodes\nodes\output.py", line 25, in export
    surface = self.get_input_link('Surface')
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\bl_nodes\node_parser.py", line 351, in get_input_link
    return self._export_node(link.from_node, link.from_socket.identifier)
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\bl_nodes\node_parser.py", line 294, in _export_node
    node_item = node_parser.export()
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\bl_nodes\nodes\shader.py", line 56, in export
    specular = self.get_input_value('Specular')
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\bl_nodes\node_parser.py", line 356, in get_input_value
    val = self.get_input_link(in_key)
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\bl_nodes\node_parser.py", line 351, in get_input_link
    return self._export_node(link.from_node, link.from_socket.identifier)
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\bl_nodes\node_parser.py", line 294, in _export_node
    node_item = node_parser.export()
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\bl_nodes\nodes\texture.py", line 31, in export
    img_path = cache_image_file(image)
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\utils\image.py", line 54, in cache_image_file
    image.file_format = old_file_format
TypeError: bpy_struct: item.attr = val: enum "" not found in ('BMP', 'IRIS', 'PNG', 'JPEG', 'JPEG2000', 'TARGA', 'TARGA_RAW', 'CINEON', 'DPX', 'OPEN_EXR_MULTILAYER', 'OPEN_EXR', 'HDR', 'TIFF', 'AVI_JPEG', 'AVI_RAW', 'FFMPEG')

2021-12-01 17:04:16,163 ERROR hdusd.engine [19464]:  Accessed schema on invalid prim, EXCEPTION:, Traceback (most recent call last):
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\engine\engine.py", line 85, in render
    self.engine.render(depsgraph)
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\engine\final_engine.py", line 160, in render
    self._render(scene)
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\engine\final_engine.py", line 109, in _render
    self._set_scene_camera(renderer, scene)
  File "C:\Users\AMD\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\engine\final_engine.py", line 146, in _set_scene_camera
    gf_camera = usd_camera.GetCamera()
RuntimeError: Accessed schema on invalid prim
```

**Comment by ARozghon** [comment]
this scene used DDS textures and USD Hydra not supported DDS file format

**Comment by bsavery** [comment]
Fine, but we should not error here.

**Comment by bnagirniak** [comment]
Should be fixed in #165

**Comment by DagerD** [comment]
@smeunier-amd Please confirm that issue is fixed with latest release.

**Comment by smeunier-amd** [comment]
@DagerD Should I use this [tag](https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon/releases/tag/v1.0.65) ?

**Comment by DagerD** [comment]
Yes.

**Comment by smeunier-amd** [comment]
I tried to render a reference using this version. Not crash anymore but everything was purple.

**Comment by DagerD** [comment]
Strange, because I have good results.

Do you have any useful messages in console? What is your video card, driver?

<details>
  <summary>Images</summary>
![image](https://user-images.githubusercontent.com/42409851/148754603-69677351-0a78-40ad-9840-24cd51f0f099.png)
![image](https://user-images.githubusercontent.com/42409851/148754616-cd0dec04-bcd3-4c2e-9fc0-99f81c2bdb7d.png)
![image](https://user-images.githubusercontent.com/42409851/148754652-4b8e25d9-4856-444c-abf7-1aa1af6ebae8.png)
</details>

**Comment by smeunier-amd** [comment]
Here's my [DxDiag] output. (https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon/files/7839898/DxDiag.txt)

**Comment by smeunier-amd** [comment]
Console reports a mountain of :
```
*** Validation warnings for  ***
Invalid element name: <materialx name="tmpMaterial.16696.743.mtlx" version="1.38" xmlns:xi="http://www.w3.org/2001/XInclude">
*** Validation warnings for  ***
Invalid element name: <materialx name="tmpMaterial.16696.744.mtlx" version="1.38" xmlns:xi="http://www.w3.org/2001/XInclude">
*** Validation warnings for  ***
Invalid element name: <materialx name="tmpMaterial.16696.745.mtlx" version="1.38" xmlns:xi="http://www.w3.org/2001/XInclude">
*** Validation warnings for  ***
Invalid element name: <materialx name="tmpMaterial.16696.746.mtlx" version="1.38" xmlns:xi="http://www.w3.org/2001/XInclude">
*** Validation warnings for  ***
Invalid element name: <materialx name="tmpMaterial.16696.747.mtlx" version="1.38" xmlns:xi="http://www.w3.org/2001/XInclude">
*** Validation warnings for  ***
Invalid element name: <materialx name="tmpMaterial.16696.748.mtlx" version="1.38" xmlns:xi="http://www.w3.org/2001/XInclude">
*** Validation warnings for  ***
Invalid element name: <materialx name="tmpMaterial.16696.749.mtlx" version="1.38" xmlns:xi="http://www.w3.org/2001/XInclude">
```

**Comment by VascoPi** [comment]
![image](https://user-images.githubusercontent.com/42581166/148904921-cb9bb8a2-4feb-4786-9524-0754c36a8351.png)
Confirm works well with the latest build
Windows 10
Radeon Vega56

**Comment by DagerD** [comment]
Also tested with HybridPro and I have the same in console as you and no result after rendering. Can you please try Full quality?

**Comment by smeunier-amd** [comment]
![image](https://user-images.githubusercontent.com/83636719/148923750-b28a982a-ba83-4444-adae-2e5951a59b6d.png)
It works with Full, no error in the console.

**Comment by DagerD** [comment]
Good. We will to try figure out what is the problem. Thanks for the report.
