### ISSUE TITLE
lib import error in Linux Mint

### ISSUE THREAD

**Issue by cgvirus** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#183]
Hello,
in Mint 20 seems like lib python is not properly linked.

```
Modules Installed (hdusd) from '/home/production/Desktop/BlenderUSDHydraAddon_1.0.65_Ubuntu20.zip' into '/home/production/.config/blender/3.0/scripts/addons'
2022-01-11 03:08:14,966 INFO hdusd.init [139722004775424]:  Loading USD Hydra addon version=(1, 0, 65), build=2592849
Traceback (most recent call last):
  File "/home/production/Apps/Graphic_Apps/Blender/3.0/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/production/.config/blender/3.0/scripts/addons/hdusd/__init__.py", line 39, in <module>
    from . import engine, properties, ui, usd_nodes, mx_nodes, bl_nodes
  File "/home/production/.config/blender/3.0/scripts/addons/hdusd/engine/__init__.py", line 39, in <module>
    from . import engine, handlers
  File "/home/production/.config/blender/3.0/scripts/addons/hdusd/engine/engine.py", line 21, in <module>
    from ..utils.stage_cache import CachedStage
  File "/home/production/.config/blender/3.0/scripts/addons/hdusd/utils/stage_cache.py", line 15, in <module>
    from pxr import Usd
  File "/home/production/.config/blender/3.0/scripts/addons/hdusd/libs/lib/python/pxr/Usd/__init__.py", line 24, in <module>
    from pxr import Tf
  File "/home/production/.config/blender/3.0/scripts/addons/hdusd/libs/lib/python/pxr/Tf/__init__.py", line 163, in <module>
    PreparePythonModule()
  File "/home/production/.config/blender/3.0/scripts/addons/hdusd/libs/lib/python/pxr/Tf/__init__.py", line 88, in PreparePythonModule
    module = importlib.import_module(
  File "/home/production/Apps/Graphic_Apps/Blender/3.0/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libpython3.9.so.1.0: cannot open shared object file: No such file or directory
 
```

**Comment by DagerD** [comment]
Hi. Do you have libpython3.9 properly installed?

**Comment by cgvirus** [comment]
Fixed. Thanks.
Required package was `libpython3.9`
