### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by IRONIC3D** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#196]
Hi

I'm trying to build from source to perform a more comprehensive tests as the current release version is causing all sorts of issues with 2.93.7 (e.g. I can no longer transform any object from the properties panel or directly, only through a transform node which needs to be filtered and then it's a mess on how to combine it back into the scene)

So, new windows 11 VM with:

- Blender 2.93.7
- Python 3.9.7 x64

- numpy
- requests
- PyOpenGL
- PySide2
- Visual Studio 2017 Community
- CMake 3.23

The build chugs along nicely and installs USD successfully, and I've added the paths recommended
``` text
adding c:\src\BlenderUSDHydraAddon\bin\USD\Install\lib\python to PYTHONPATH
adding c:\src\BlenderUSDHydraAddon\bin\USD\install\bin to PATH
adding c:\src\BlenderUSDHydraAddon\bin\USD\install\lib to PATH
```

Then it falls apart when trying to build hdRPR
``` cmd
-------------------------------------------------------------
Building HdRPR
-------------------------------------------------------------
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
CMake Warning at cmake/defaults/ProjectDefaults.cmake:34 (message):
  Building USD on Windows is currently experimental.
Call Stack (most recent call first):
  CMakeLists.txt:10 (include)


-- Configuring usdview plugin
CMake Error at cmake/defaults/Packages.cmake:59 (find_program):
  Could not find USD_SCHEMA_GENERATOR using the following names:
  usdGenSchema.py, usdGenSchema
Call Stack (most recent call first):
  CMakeLists.txt:11 (include)


-- Configuring incomplete, errors occurred!
See also "C:/src/BlenderUSDHydraAddon/deps/HdRPR/build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "C:\src\BlenderUSDHydraAddon\tools\build.py", line 189, in <module>
    main()
  File "C:\src\BlenderUSDHydraAddon\tools\build.py", line 171, in main
    hdrpr(bin_dir, args.G, args.j, args.clean)
  File "C:\src\BlenderUSDHydraAddon\tools\build.py", line 96, in hdrpr
    _cmake(hdrpr_dir, compiler, jobs, [
  File "C:\src\BlenderUSDHydraAddon\tools\build.py", line 78, in _cmake
    subprocess.check_call(['cmake', *build_args])
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-B', 'build', '-Dpxr_DIR=C:\\src\\BlenderUSDHydraAddon\\bin\\USD\\install', '-DCMAKE_INSTALL_PREFIX=C:\\src\\BlenderUSDHydraAddon\\bin\\USD\\install', '-DRPR_BUILD_AS_HOUDINI_PLUGIN=FALSE', '-G', 'Visual Studio 15 2017 Win64']' returned non-zero exit status 1.
```

The CMakeOutput.log doesn't show any errors so it's not helpful.

Any ideas?

Thank you

**Comment by IRONIC3D** [comment]
> Try to install python module jinja2. In #198 we have updated README with new recommendations.

Hi @bnagirniak , thank you for the tip, but no bueno

I've tried a fresh build using VC 2019 as advised in #198 . I got far but not that far, after 36 GB of generated files I've reached this far:

```cmd
-- Build files have been written to: C:/src/BlenderUSDHydraAddon/deps/HdRPR/build
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Generating __init__.pyc
  Generating devicesConfiguration.pyc
  Building Custom Rule C:/src/BlenderUSDHydraAddon/deps/HdRPR/pxr/imaging/rprUsd/CMakeLists.txt
  Building Custom Rule C:/src/BlenderUSDHydraAddon/deps/HdRPR/pxr/imaging/rprUsd/CMakeLists.txt
  Building Custom Rule C:/src/BlenderUSDHydraAddon/deps/HdRPR/deps/CMakeLists.txt
  RadeonProRenderCpp.cpp
  tinyxml2.cpp
  cpprpr.vcxproj -> C:\src\BlenderUSDHydraAddon\deps\HdRPR\build\deps\Release\cpprpr.lib
  Generating schema/api.h, schema/tokens.h, schema/rendererSettingsAPI.h, schema/objectSettingsAPI.h, schema/meshSettingsAPI.h, schema/materialSettingsAPI.h, s
  chema/domeLightSettingsAPI.h, schema/tokens.cpp, schema/rendererSettingsAPI.cpp, schema/objectSettingsAPI.cpp, schema/meshSettingsAPI.cpp, schema/materialSet
  tingsAPI.cpp, schema/domeLightSettingsAPI.cpp, schema/wrapTokens.cpp, schema/wrapRendererSettingsAPI.cpp, schema/wrapObjectSettingsAPI.cpp, schema/wrapMeshSe
  ttingsAPI.cpp, schema/wrapMaterialSettingsAPI.cpp, schema/wrapDomeLightSettingsAPI.cpp, schema/plugInfo.json, schema/generatedSchema.usda
  #################################################################################################
  #  USD_DISABLE_PRIM_DEFINITIONS_FOR_USDGENSCHEMA is overridden to 'true'.  Default is 'false'.  #
  #################################################################################################
CUSTOMBUILD : error :  [C:\src\BlenderUSDHydraAddon\deps\HdRPR\build\pxr\imaging\rprUsd\rprUsdSchema.vcxproj]
          Error in 'pxrInternal_v0_21__pxrReserved__::PlugPlugin::_Load' at line 258 in file C:\src\BlenderUSDHydraAddon\deps\USD\pxr\base\plug\plugin.cpp : 'F
  ailed to load plugin 'usd': A dynamic link library (DLL) initialization routine failed.

   in 'c:/src/BlenderUSDHydraAddon/bin/USD/install/lib/usd_usd.dll''
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'C:
\src\BlenderUSDHydraAddon\deps\HdRPR\build\CMakeFiles\d793060c59b165284c5166b212fbd844\api.h.rule;C:\src\BlenderUSDHydraAddon\deps\HdRPR\build\CMakeFiles\df04f
6ee9d0d9c6728cd8bed108836c2\rprUsdSchema.rule;C:\src\BlenderUSDHydraAddon\deps\HdRPR\pxr\imaging\rprUsd\CMakeLists.txt' exited with code 1. [C:\src\BlenderUSDH
ydraAddon\deps\HdRPR\build\pxr\imaging\rprUsd\rprUsdSchema.vcxproj]
Traceback (most recent call last):
  File "C:\src\BlenderUSDHydraAddon\tools\build.py", line 189, in <module>
    main()
  File "C:\src\BlenderUSDHydraAddon\tools\build.py", line 171, in main
    hdrpr(bin_dir, args.G, args.j, args.clean)
  File "C:\src\BlenderUSDHydraAddon\tools\build.py", line 96, in hdrpr
    _cmake(hdrpr_dir, compiler, jobs, [
  File "C:\src\BlenderUSDHydraAddon\tools\build.py", line 79, in _cmake
    subprocess.check_call(['cmake', *compile_args])
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', 'build', '--config', 'Release', '--target', 'install']' returned non-zero exit status 1.
```

Any advise?

Next step is scrap everything and start again with 2017. All limbs crossed :)

**Comment by IRONIC3D** [comment]
Same issue with 2017

```cmd
Building HdRPR
-------------------------------------------------------------
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
CMake Warning at cmake/defaults/ProjectDefaults.cmake:34 (message):
  Building USD on Windows is currently experimental.
Call Stack (most recent call first):
  CMakeLists.txt:10 (include)


-- Configuring usdview plugin
-- C++ namespace configured to (external) pxr, (internal) pxrInternal_v0_21
-- Configuring done
-- Generating done
-- Build files have been written to: C:/src/BlenderUSDHydraAddon/deps/HdRPR/build
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  cpprpr.vcxproj -> C:\src\BlenderUSDHydraAddon\deps\HdRPR\build\deps\Release\cpprpr.lib
  Generating schema/api.h, schema/tokens.h, schema/rendererSettingsAPI.h, schema/objectSettingsAPI.h, schema/meshSettingsAPI.h, schema/materialSettingsAPI.h, sc
  hema/domeLightSettingsAPI.h, schema/tokens.cpp, schema/rendererSettingsAPI.cpp, schema/objectSettingsAPI.cpp, schema/meshSettingsAPI.cpp, schema/materialSetti
  ngsAPI.cpp, schema/domeLightSettingsAPI.cpp, schema/wrapTokens.cpp, schema/wrapRendererSettingsAPI.cpp, schema/wrapObjectSettingsAPI.cpp, schema/wrapMeshSetti
  ngsAPI.cpp, schema/wrapMaterialSettingsAPI.cpp, schema/wrapDomeLightSettingsAPI.cpp, schema/plugInfo.json, schema/generatedSchema.usda
  #################################################################################################
  #  USD_DISABLE_PRIM_DEFINITIONS_FOR_USDGENSCHEMA is overridden to 'true'.  Default is 'false'.  #
  #################################################################################################
CUSTOMBUILD : error :  [C:\src\BlenderUSDHydraAddon\deps\HdRPR\build\pxr\imaging\rprUsd\rprUsdSchema.vcxproj]
          Error in 'pxrInternal_v0_21__pxrReserved__::PlugPlugin::_Load' at line 258 in file C:\src\BlenderUSDHydraAddon\deps\USD\pxr\base\plug\plugin.cpp : 'Fa
  iled to load plugin 'usd': A dynamic link library (DLL) initialization routine failed.

   in 'c:/src/BlenderUSDHydraAddon/bin/USD/install/lib/usd_usd.dll''
Traceback (most recent call last):
  File "C:\src\BlenderUSDHydraAddon\tools\build.py", line 189, in <module>
    main()
  File "C:\src\BlenderUSDHydraAddon\tools\build.py", line 171, in main
    hdrpr(bin_dir, args.G, args.j, args.clean)
  File "C:\src\BlenderUSDHydraAddon\tools\build.py", line 96, in hdrpr
    _cmake(hdrpr_dir, compiler, jobs, [
  File "C:\src\BlenderUSDHydraAddon\tools\build.py", line 79, in _cmake
    subprocess.check_call(['cmake', *compile_args])
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', 'build', '--config', 'Release', '--target', 'install']' returned non-zero exit status 1.
```

Not sure why the DLL is not loading, could it be because of the VM?

**Comment by bnagirniak** [comment]
@IRONIC3D did you install python jinja2 module for python3.9? 
`pip install jinja2`

**Comment by IRONIC3D** [comment]
Hi @bnagirniak Yes I did, this is after I've installed jinja2

```cmd
pip install jinja2
Requirement already satisfied: jinja2 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (3.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from jinja2) (2.1.0)
WARNING: You are using pip version 21.2.3; however, version 22.0.3 is available.
You should consider upgrading via the 'C:\Users\User\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.
```

**Comment by IRONIC3D** [comment]
@bnagirniak, what I mean is that error message about 

``` cmd
CUSTOMBUILD : error :  [C:\src\BlenderUSDHydraAddon\deps\HdRPR\build\pxr\imaging\rprUsd\rprUsdSchema.vcxproj]
          Error in 'pxrInternal_v0_21__pxrReserved__::PlugPlugin::_Load' at line 258 in file C:\src\BlenderUSDHydraAddon\deps\USD\pxr\base\plug\plugin.cpp : 'Fa
  iled to load plugin 'usd': A dynamic link library (DLL) initialization routine failed.
```

is appearing after installing jinja2.  Before installing jinja2 I was getting a different error about building hdRPR.

**Comment by bnagirniak** [comment]
Can't say exactly the reason of such problem, our team didn't see it before. Maybe it happen because of Windows 11 and VM.
Can you try open HdRPR project in VS, it should be in `deps\HdRPR\build`, and build project here. It should show you more info about the error.

**Comment by IRONIC3D** [comment]
Thanks, still got an error when building from VS2019

```cmd
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB8066	Custom build for 'C:\src\BlenderUSDHydraAddon\deps\HdRPR\build\CMakeFiles\d793060c59b165284c5166b212fbd844\api.h.rule;C:\src\BlenderUSDHydraAddon\deps\HdRPR\build\CMakeFiles\df04f6ee9d0d9c6728cd8bed108836c2\rprUsdSchema.rule;C:\src\BlenderUSDHydraAddon\deps\HdRPR\pxr\imaging\rprUsd\CMakeLists.txt' exited with code 1.	rprUsdSchema	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	241	

```

But reverting back to trace what is happening I've noticed something that keeps reoccurring (since I'm rebuilding from scratch all the time)

Running python tools/build.py -all -bin-dir bin goes like this:

1- Fetches all archives for openSubdiv, openvdb, exr..etc
2- says succeed and instruct to set up the environment variables for USD (which I do)
3- Builds hyRPR and reaches a point where it is copying binaries to libs
4- that is when the first error happens "FileNotFoundError: [Errno 2] No such file or directory: 'bin\\USD\\install\\bin'" the folder is missing indeed and the repo size is at 20GB at this time
5- I run the same command again "python tools/build.py -all -bin-dir bin" and this is where it starts building USD this time instead of hyRPR and gives me the same notice to put the environment variables, then succeeds
6- then it tries to build hyRPR and it fails like so:

```cmd
  #################################################################################################
  #  USD_DISABLE_PRIM_DEFINITIONS_FOR_USDGENSCHEMA is overridden to 'true'.  Default is 'false'.  #
  #################################################################################################
CUSTOMBUILD : error :  [C:\src\BlenderUSDHydraAddon\deps\HdRPR\build\pxr\imaging\rprUsd\rprUsdSchema.vcxproj]
          Error in 'pxrInternal_v0_21__pxrReserved__::PlugPlugin::_Load' at line 258 in file C:\src\BlenderUSDHydraAddon\deps\USD\pxr\base\p
  lug\plugin.cpp : 'Failed to load plugin 'usd': A dynamic link library (DLL) initialization routine failed.

   in 'c:/src/BlenderUSDHydraAddon/bin/USD/install/lib/usd_usd.dll''
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: C
ustom build for 'C:\src\BlenderUSDHydraAddon\deps\HdRPR\build\CMakeFiles\d793060c59b165284c5166b212fbd844\api.h.rule;C:\src\BlenderUSDHydraA
ddon\deps\HdRPR\build\CMakeFiles\df04f6ee9d0d9c6728cd8bed108836c2\rprUsdSchema.rule' exited with code 1. [C:\src\BlenderUSDHydraAddon\deps\H
dRPR\build\pxr\imaging\rprUsd\rprUsdSchema.vcxproj]
```

Might try building natively today sometimes. Thanks for all your help

**Comment by IRONIC3D** [comment]
It's amazing how tracing the output can be helpful :) it works now.

So the 1st time I build the project I am requested to add the <pproject source tree>\deps\USD oaths into the PYTHONPATH and then PATH.

the 2nd time I build the program the USD is build and now I am requested to add the \bin\USD\... into the PYTHONPATH and PATH.

I don't believe you you had the need to rebuild the whole thing from scratch like I did, and once the USD is built there is no need to rebuild it again, perhaps that is why it didn't happen to you. But once the path is updated the second time everything works fine and now I have a new build for the BlenderHydra addon.

Now to put it to the test.
