### ISSUE TITLE
unable to enable it 

### ISSUE THREAD

**Issue by xalteropsx** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#237]
``bpy.context.space_data.system_bookmarks_active = 3
Modules Installed (hdusd) from 'C:\\Users\\haide\\Downloads\\BlenderUSDHydraAddon_1.0.65_Windows.zip' into 'C:\\Users\\haide\\AppData\\Roaming\\Blender Foundation\\Blender\\3.1\\scripts\\addons'
Traceback (most recent call last):
  File "X:\BnSModding\blender\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\hdusd\__init__.py", line 39, in <module>
    from . import engine, properties, ui, usd_nodes, mx_nodes, bl_nodes
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\hdusd\engine\__init__.py", line 39, in <module>
    from . import engine, handlers
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\hdusd\engine\engine.py", line 21, in <module>
    from ..utils.stage_cache import CachedStage
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\hdusd\utils\stage_cache.py", line 15, in <module>
    from pxr import Usd
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\hdusd\libs\lib\python\pxr\Usd\__init__.py", line 24, in <module>
    from pxr import Tf
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\hdusd\libs\lib\python\pxr\Tf\__init__.py", line 163, in <module>
    PreparePythonModule()
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\hdusd\libs\lib\python\pxr\Tf\__init__.py", line 88, in PreparePythonModule
    module = importlib.import_module(
  File "X:\BnSModding\blender\3.1\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _tf: The specified module could not be found.

Python: Traceback (most recent call last):
  File "X:\BnSModding\blender\3.1\scripts\startup\bl_operators\userpref.py", line 782, in execute
    shutil.rmtree(path)
  File "X:\BnSModding\blender\3.1\python\lib\shutil.py", line 739, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "X:\BnSModding\blender\3.1\python\lib\shutil.py", line 617, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "X:\BnSModding\blender\3.1\python\lib\shutil.py", line 615, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\haide\\AppData\\Roaming\\Blender Foundation\\Blender\\3.1\\scripts\\addons\\hdusd\\hdusd.log'

location: <unknown location>:-1

``

**Comment by DagerD** [comment]
Hi.

For Blender 3.1 please download our latest build with 3.10 Python [BlenderUSDHydraAddon_1.0.92_3.10_Windows.zip](https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon/releases/download/v1.0.92/BlenderUSDHydraAddon_1.0.92_3.10_Windows.zip)

**Comment by ultra-sonic** [comment]
I have the same issue on Centos 7.7 Linux with blender 3.1.2 using python 3.10
`
Read prefs: /home/olimar/.config/blender/3.1/config/userpref.blend
2022-05-20 17:25:13,421 INFO hdusd.init [140579243983232]:  Loading USD Hydra addon version=(1, 0, 97), build=8416bf5
Traceback (most recent call last):
  File "/usr/local/blender/blender-3.1.2-linux-x64/3.1/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/raid/standards/base-setups/blender/production/3.1/scripts/addons/hdusd/__init__.py", line 108, in <module>
    from . import engine, properties, ui, usd_nodes, mx_nodes, bl_nodes
  File "/raid/standards/base-setups/blender/production/3.1/scripts/addons/hdusd/engine/__init__.py", line 43, in <module>
    from . import engine, handlers
  File "/raid/standards/base-setups/blender/production/3.1/scripts/addons/hdusd/engine/engine.py", line 21, in <module>
    from ..utils.stage_cache import CachedStage
  File "/raid/standards/base-setups/blender/production/3.1/scripts/addons/hdusd/utils/stage_cache.py", line 15, in <module>
    from pxr import Usd
  File "/mutter/users/olimar/hdusd/libs-3.10/lib/python/pxr/Usd/__init__.py", line 24, in <module>
    from pxr import Tf
  File "/mutter/users/olimar/hdusd/libs-3.10/lib/python/pxr/Tf/__init__.py", line 163, in <module>
    PreparePythonModule()
  File "/mutter/users/olimar/hdusd/libs-3.10/lib/python/pxr/Tf/__init__.py", line 88, in PreparePythonModule
    module = importlib.import_module(
  File "/usr/local/blender/blender-3.1.2-linux-x64/3.1/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libpython3.10.so.1.0: cannot open shared object file: No such file or directory
`

`
find /usr/local/blender/ -name "*libpython*"
`
gives me:
`
/usr/local/blender/blender-3.1.2-linux-x64/3.1/python/lib/python3.10/config-3.10-x86_64-linux-gnu/libpython3.10.a
/usr/local/blender/blender-3.1.2-linux-x64/3.1/python/lib/python3.10/site-packages/Cython/Debugger/libpython.py
/usr/local/blender/blender-3.1.2-linux-x64/3.1/python/lib/python3.10/site-packages/Cython/Debugger/Tests/test_libpython_in_gdb.py
`
not sure why it wants to import the libpython3.10.so.1.0 and not libpython3.10.a

any ideas?

thanks a lot and have a great weekend!

**Comment by masahiroteraoka** [comment]
Hello, Thank you for this exciting addon! it works in my windows11 with blender 3.1.2, but unfortunately doesn't work in linux mint with same 3.1.2. Seems like kinda same issue which ultra-sonic said.

`2022-05-28 08:43:14,983 INFO hdusd.init [139899604664704]:  Loading USD Hydra addon version=(1, 0, 95), build=ca41f09
Traceback (most recent call last):
  File "/home/mteraoka/software/blender-3.1.2-linux-x64/3.1/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/mteraoka/.config/blender/3.1/scripts/addons/hdusd/__init__.py", line 37, in <module>
    from . import engine, properties, ui, usd_nodes, mx_nodes, bl_nodes
  File "/home/mteraoka/.config/blender/3.1/scripts/addons/hdusd/engine/__init__.py", line 43, in <module>
    from . import engine, handlers
  File "/home/mteraoka/.config/blender/3.1/scripts/addons/hdusd/engine/engine.py", line 21, in <module>
    from ..utils.stage_cache import CachedStage
  File "/home/mteraoka/.config/blender/3.1/scripts/addons/hdusd/utils/stage_cache.py", line 15, in <module>
    from pxr import Usd
  File "/home/mteraoka/.config/blender/3.1/scripts/addons/hdusd/libs-3.10/lib/python/pxr/Usd/__init__.py", line 24, in <module>
    from pxr import Tf
  File "/home/mteraoka/.config/blender/3.1/scripts/addons/hdusd/libs-3.10/lib/python/pxr/Tf/__init__.py", line 163, in <module>
    PreparePythonModule()
  File "/home/mteraoka/.config/blender/3.1/scripts/addons/hdusd/libs-3.10/lib/python/pxr/Tf/__init__.py", line 88, in PreparePythonModule
    module = importlib.import_module(
  File "/home/mteraoka/software/blender-3.1.2-linux-x64/3.1/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libpython3.10.so.1.0: cannot open shared object file: No such file or directory
` 
Thank you very much, in advance!

**Comment by xalteropsx** [comment]
https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon/releases

thnx the weekly update of urs solve the bug but above link expire 
thank u again for quick fix

**Comment by DagerD** [comment]
@masahiroteraoka @ultra-sonic 

Try to run `apt install libpython3.10`.

**Comment by ultra-sonic** [comment]
why would i need to install this when i'm already inside of a 3.10 interpreter?

**Comment by DagerD** [comment]
Because on Unix-like systems you very often don't have required packages.

**Comment by Nikita-schetko** [comment]
Guys, is there a solution for that problem? Cannot use it on macOs 12.4 Monterey

**Comment by bsavery** [comment]
There is a blender side issue that doesn't allow us to import USD libraries.  We're trying to find another solution but there has to be a change on the blender side.

**Comment by xalteropsx** [comment]
![image](https://user-images.githubusercontent.com/103671642/175373247-d847b069-24ba-4a30-9a28-1440b8fd230b.png)
new issue has been arrise black screen

**Comment by xalteropsx** [comment]
rpr not working on GL work which is slow

**Comment by xalteropsx** [comment]
rx 580 gpu bug issue 3.10.2 blender

**Comment by DagerD** [comment]
Could you please close this issue if it has been resolved and open a new one with attached scene and logs from console?

**Comment by xalteropsx** [comment]
2022-06-24 17:40:57,875 INFO hdusd.init [8868]:  Loading USD Hydra addon version=(1, 1, 2), build=efbe19d
###################################################################################
#  HD_ENABLE_SCENE_INDEX_EMULATION is overridden to 'false'.  Default is 'true'.  #
###################################################################################
2022-06-24 17:41:03,725 WARNING hdusd.bl_nodes [8868]:  Ignoring unsupported UV Map, TANGENT, <bpy_struct, ShaderNodeNormalMap("Normal Map") at 0x0000018C4912C408>, <bpy_struct, Material("col1") at 0x0000018C41C1E988>, No UV Map will be used
[RPR ERROR] Failed to create RPR context -- invalid api version in RprUsdCreateContext at line 410 of C:\JN\WS\BlenderUSDHydraPlugin_Build\BlenderUSDHydraAddon\deps\HdRPR\pxr\imaging\rprUsd\contextHelpers.cpp(a8cd939)
@DagerD  sorry sir for late reply

**Comment by xalteropsx** [comment]
``Read prefs: C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.1\config\userpref.blend
2022-06-24 17:44:47,993 INFO rpr.engine.init [15784]:  Core version: 2.2.12 build 0x4382e327
2022-06-24 17:44:48,003 INFO rpr.engine.init [15784]:  RIF version: 1.7.1 build 0xfdc139ba
Error: Required device extension VK_KHR_deferred_host_operations is not supported.
2022-06-24 17:44:48,067 WARNING rpr.engine.init [15784]:  ('Plugin is not registered', WindowsPath('C:/Users/haide/AppData/Roaming/Blender Foundation/Blender/3.1/scripts/addons/rprblender/HybridPro.dll'), '')
2022-06-24 17:44:48,894 INFO rpr.material_library [15784]:  Material library located at C:\ProgramData\RadeonProRender\MaterialLibrary\Xml
Zen UV Library: REGISTERED.
Load Handler:
Scanning directory: C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Vera Lighting Studio\thumbs/c
Traceback (most recent call last):
  File "X:\BnSModding\blender\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\hdusd\__init__.py", line 39, in <module>
    from .utils import logging, temp_dir
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\hdusd\utils\__init__.py", line 46, in <module>
    from . import logging
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\hdusd\utils\logging.py", line 32, in <module>
    file_handler.doRollover()
  File "X:\BnSModding\blender\3.1\python\lib\logging\handlers.py", line 179, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "X:\BnSModding\blender\3.1\python\lib\logging\handlers.py", line 115, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\haide\\AppData\\Roaming\\Blender Foundation\\Blender\\3.1\\scripts\\addons\\hdusd\\hdusd.log' -> 'C:\\Users\\haide\\AppData\\Roaming\\Blender Foundation\\Blender\\3.1\\scripts\\addons\\hdusd\\hdusd.log.1'

Traceback (most recent call last):
  File "X:\BnSModding\blender\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\hdusd\__init__.py", line 39, in <module>
    from .utils import logging, temp_dir
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\hdusd\utils\__init__.py", line 46, in <module>
    from . import logging
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\hdusd\utils\logging.py", line 32, in <module>
    file_handler.doRollover()
  File "X:\BnSModding\blender\3.1\python\lib\logging\handlers.py", line 179, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "X:\BnSModding\blender\3.1\python\lib\logging\handlers.py", line 115, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\haide\\AppData\\Roaming\\Blender Foundation\\Blender\\3.1\\scripts\\addons\\hdusd\\hdusd.log' -> 'C:\\Users\\haide\\AppData\\Roaming\\Blender Foundation\\Blender\\3.1\\scripts\\addons\\hdusd\\hdusd.log.1'

2022-06-24 17:45:25,349 INFO hdusd.init [15784]:  Loading USD Hydra addon version=(1, 1, 2), build=efbe19d
###################################################################################
#  HD_ENABLE_SCENE_INDEX_EMULATION is overridden to 'false'.  Default is 'true'.  #
###################################################################################
[RPR ERROR] Failed to create RPR context -- invalid api version in RprUsdCreateContext at line 410 of C:\JN\WS\BlenderUSDHydraPlugin_Build\BlenderUSDHydraAddon\deps\HdRPR\pxr\imaging\rprUsd\contextHelpers.cpp(a8cd939)
``

**Comment by xalteropsx** [comment]
i guess it resolve on new blender version 3.2
