### ISSUE TITLE
UsdImagingLite ?

### ISSUE THREAD

**Issue by pellerington** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#33]
Hello,

I am trying to get this running on linux using "../blender-2.91.0-linux64/blender --python cmd_tools/test_plugin.py"
It's running into the issue saying it requires UsdImagingLite (I will leave the error log below).

What is UsdImagingLite? It gives up zero results on google and github only gives one result which is this repo.

Is it from an older version of USD or something?

Traceback (most recent call last):
  File "/BlenderUSDHydraAddon/cmd_tools/test_plugin.py", line 30, in <module>
    import hdusd
  File "/BlenderUSDHydraAddon/src/hdusd/__init__.py", line 39, in <module>
    from . import engine, properties, ui, usd_nodes, mx_nodes
  File "/BlenderUSDHydraAddon/src/hdusd/engine/__init__.py", line 32, in <module>
    from . import engine, handlers
  File "/BlenderUSDHydraAddon/src/hdusd/engine/engine.py", line 71, in <module>
    from . import final_engine, viewport_engine, preview_engine
  File "/BlenderUSDHydraAddon/src/hdusd/engine/final_engine.py", line 19, in <module>
    from pxr import UsdImagingGL, UsdImagingLite
ImportError: cannot import name 'UsdImagingLite' from 'pxr' (/blender-2.91.0-linux64/2.91/python/lib/python3.7/pxr/__init__.py)

Thanks,
Peter

**Comment by bnagirniak** [comment]
Sorry, UsdImagingLite is in our closed repo of USD. We have nearest plans to move its code into this repo, so it'll be available there soon.

**Comment by bnagirniak** [comment]
For your development, you can temporary comment code with UsdImagingLite, it is used only in final_engine.py. Final rendering won't be available for RPR delegate but will work for GL delegate.

**Comment by pellerington** [comment]
Thanks I was able to launch it. I had to change:

-from pxr import UsdImagingGL, UsdImagingLite
+from pxr import UsdImagingGL

in src/hdusd/engine/final_engine.py

and also:

-        default='HdRprPlugin',
+        default='HdStormRendererPlugin',

in src/hdusd/properties/scene.py

Thank you!

**Comment by bsavery** [comment]
We're going to make it so that we can more easily work on linux.  Stay tuned!

**Comment by pellerington** [comment]
Exciting news, can't wait for the next update. Will happily test anything when it's ready.

Is the current implementation locked to the usd included delegates, or is the intention to allow any custom render delegate in the future?

**Comment by bsavery** [comment]
You should/could be able to install your own delegate right now.  But it would have to be compiled against the USD version in the plugin.  We haven't tested this but that's the intention.

**Comment by pellerington** [comment]
How do I link it, it's currently only giving me the option of GL?

**Comment by bsavery** [comment]
You'd have to install whichever hydra delegate to libs/plugins.  The code that searches for render delegates is here: 

https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon/blob/46f3f31ab67b444d10774f06f84fee25774a2c5f/src/hdusd/properties/scene.py#L22

Which delegate are you trying to use?

**Comment by pellerington** [comment]
It's a custom one (not embree/renderman/arnold or any published delegate).

I see that you are moving usdImagingLite into the repo. Thank you for the quick update!

**Comment by bnagirniak** [comment]
Yes, and Linux build is coming soon ;)

**Comment by KY-Hage** [comment]
I came across a similar issue when I was trying to install Renderman as a USD hydra delegate. I'll preface this by saying I'm not a developer. I'm just a 3D artist interested in using this system.

```
Traceback (most recent call last):
  File "D:\Blender\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\__init__.py", line 39, in <module>
    from . import engine, properties, ui, usd_nodes, mx_nodes, bl_nodes
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\engine\__init__.py", line 39, in <module>
    from . import engine, handlers
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\engine\engine.py", line 42, in <module>
    from . import final_engine, viewport_engine, preview_engine
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\engine\final_engine.py", line 19, in <module>
    from pxr import UsdImagingGL, UsdImagingLite
ImportError: cannot import name 'UsdImagingLite' from 'pxr' (C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\hdusd\libs\lib\python\pxr\__init__.py)
```

After reading the documentation [here](User) I thought it was going to be something where I just run the build_usd.py script from [Pixar USD](https://github.com/PixarAnimationStudios/USD) and enable the options in the [advanced build configuration](https://github.com/PixarAnimationStudios/USD/blob/release/BUILDING.md#advanced-build-configuration) while using the line arguments from [here](https://graphics.pixar.com/usd/docs/RenderMan-USD-Imaging-Plugin.html). I had to do a bit of folder renaming since Boost installation was failing but ultimately the traceback above was, what I think, the closest I got to installing the delegate.

After spending an embarrassing amount of time trying to figure this out I am stuck. If someone could lend some guidance on how to correctly add a delegate I would be very grateful.

Thanks!

**Comment by bnagirniak** [comment]
Try the following:
1. Add your options for build_usd.py script from Pixar USD here: https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon/blob/master/tools/build_usd.py#L64
2. Use our build tool https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#build-tool to build USD and all other projects required for this plugin.

**Comment by bnagirniak** [comment]
@KY-Hage in your case from #111 it'll be:
```
        call_args = (sys.executable, str(usd_dir / "build_scripts/build_usd.py"),
                     '--build', str(bin_usd_dir / "build"),
                     '--src', str(bin_usd_dir / "deps"),
                     '--openvdb',
                     '--prman', '--prman-location", "C:\Program Files\Pixar\RenderManProServer-24.1",
                     str(bin_usd_dir / "install"),
                     *args)
```

**Comment by KY-Hage** [comment]
Ok so I believe the build went fine for the most part because when I looked through the folders I saw Prman (renderman) and other folders that weren't in the pre-built release. 

Unfortunately I ran into a few issues. First, I was not able to find the zip file that I am supposed to install into Blender. The documentation mentioned that it should be in the install folder but no zip was there. I checked all the other folders and couldn't find it. Maybe I was supposed to include something else in the options. I will attach an image of my folder.

![06c994e11f4efae2e21cd6992e409dc9](https://user-images.githubusercontent.com/91340634/135145817-b2102abd-5426-4715-aa1e-836ad9653763.png)




Second is that I had some errors come up at the end of my build which I copied below. This appears to be the same error message I got when using Visual Studio 2019. The one below is from Visual Studio 2017 Community.

```
S:\GitHub\BlenderUSDHydraAddon>git submodule update --init --recursive

S:\GitHub\BlenderUSDHydraAddon>python tools/build.py -all -bin-dir bin -G "Visual Studio 15 2017 Win64"
S:/GitHub/BlenderUSDHydraAddon/tools/data/USD.patch:33: trailing whitespace.
//
S:/GitHub/BlenderUSDHydraAddon/tools/data/USD.patch:34: trailing whitespace.
// Copyright 2020 Pixar
S:/GitHub/BlenderUSDHydraAddon/tools/data/USD.patch:35: trailing whitespace.
//
S:/GitHub/BlenderUSDHydraAddon/tools/data/USD.patch:36: trailing whitespace.
// Licensed under the Apache License, Version 2.0 (the "Apache License")
S:/GitHub/BlenderUSDHydraAddon/tools/data/USD.patch:37: trailing whitespace.
// with the following modification; you may not use this file except in
warning: squelched 42 whitespace errors
warning: 47 lines add whitespace errors.
Modifying: S:\GitHub\BlenderUSDHydraAddon\deps\USD\pxr\usdImaging\CMakeLists.txt
Running: ('C:\\Users\\DeRobertC\\AppData\\Local\\Programs\\Python\\Python39\\python.exe', 'S:\\GitHub\\BlenderUSDHydraAddon\\deps\\USD\\build_scripts\\build_usd.py', '--build', 'bin\\USD\\build', '--src', 'bin\\USD\\deps', '--openvdb', '--prman', '--prman-location', 'C:\\Program Files\\Pixar\\RenderManProServer-24.1', 'bin\\USD\\install')

Building with settings:
  USD source directory          S:\GitHub\BlenderUSDHydraAddon\deps\USD
  USD install directory         S:\GitHub\BlenderUSDHydraAddon\deps\USD\bin\USD\install
  3rd-party source directory    S:\GitHub\BlenderUSDHydraAddon\deps\USD\bin\USD\deps
  3rd-party install directory   S:\GitHub\BlenderUSDHydraAddon\deps\USD\bin\USD\install
  Build directory               S:\GitHub\BlenderUSDHydraAddon\deps\USD\bin\USD\build
  CMake generator               Default
  CMake toolset                 Default
  Downloader                    curl

  Building                      Shared libraries
    Config                      Release
    Imaging                     On
      Ptex support:             Off
      OpenVDB support:          On
      OpenImageIO support:      Off
      OpenColorIO support:      Off
      PRMan support:            On
    UsdImaging                  On
      usdview:                  On
    Python support              On
      Python 3:                 On
    Documentation               Off
    Tests                       Off
    Examples                    On
    Tutorials                   On
    Tools                       On
    Alembic Plugin              Off
      HDF5 support:             Off
    Draco Plugin                Off
    MaterialX Plugin            Off

  Dependencies                  zlib, boost, TBB, OpenSubdiv, Blosc, OpenEXR, OpenVDB
STATUS: Installing zlib...
STATUS: Installing boost...
STATUS: Installing TBB...
STATUS: Installing OpenSubdiv...
STATUS: Installing Blosc...
STATUS: Installing OpenEXR...
STATUS: Installing OpenVDB...
STATUS: Installing USD...

Success! To use USD, please ensure that you have:

    The following in your PYTHONPATH environment variable:
    S:\GitHub\BlenderUSDHydraAddon\deps\USD\bin\USD\install\lib\python

    The following in your PATH environment variable:
    S:\GitHub\BlenderUSDHydraAddon\deps\USD\bin\USD\install\bin
    S:\GitHub\BlenderUSDHydraAddon\deps\USD\bin\USD\install\lib

See documentation at http://openusd.org/docs/RenderMan-USD-Imaging-Plugin.html for setting up the RenderMan plugin.

Reverting USD repo
Removing pxr/imaging/hioOpenVDB/api.h
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.16.27045.0
-- The CXX compiler identification is MSVC 19.16.27045.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at cmake/defaults/ProjectDefaults.cmake:34 (message):
  Building USD on Windows is currently experimental.
Call Stack (most recent call first):
  CMakeLists.txt:10 (include)


-- Could NOT find pxr (missing: pxr_DIR)
FATALCould not find hython executable
-- Could NOT find HoudiniUSD (missing: Houdini_USD_INCLUDE_DIR Houdini_USD_LIB_DIR Houdini_USD_IMPLIB_DIR Houdini_Python_INCLUDE_DIR Houdini_Python_LIB Houdini_Boostpython_LIB HYTHON_EXECUTABLE)
CMake Error at cmake/defaults/Packages.cmake:55 (message):
  Required: USD install or Houdini with included USD.
Call Stack (most recent call first):
  CMakeLists.txt:11 (include)


-- Configuring incomplete, errors occurred!
See also "S:/GitHub/BlenderUSDHydraAddon/deps/HdRPR/build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "S:\GitHub\BlenderUSDHydraAddon\tools\build.py", line 181, in <module>
    main()
  File "S:\GitHub\BlenderUSDHydraAddon\tools\build.py", line 162, in main
    hdrpr(bin_dir, args.G, args.j, args.clean)
  File "S:\GitHub\BlenderUSDHydraAddon\tools\build.py", line 77, in hdrpr
    _cmake(hdrpr_dir, compiler, jobs, [
  File "S:\GitHub\BlenderUSDHydraAddon\tools\build.py", line 62, in _cmake
    subprocess.check_call(['cmake', *build_args])
  File "C:\Users\DeRobertC\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-B', 'build', '-Dpxr_DIR=bin\\USD\\install', '-DCMAKE_INSTALL_PREFIX=bin\\HdRPR\\install', '-DRPR_BUILD_AS_HOUDINI_PLUGIN=FALSE', '-G', 'Visual Studio 15 2017 Win64']' returned non-zero exit status 1.

S:\GitHub\BlenderUSDHydraAddon>
```


Thanks again for taking the time to try and help me get this set up.

**Comment by bnagirniak** [comment]
Thank you for your detailed report, we still haven't tried renderman delegate, but it is in our plans. We expect there could be issues with new delegate. 

> -GL Renderer objects never have color.

This is known issue, it'll be fixed soon.

Overall, we'll walk with your report and such fixes are in our plans.
