### ISSUE TITLE
Traceback error on load

### ISSUE THREAD

**Issue by pavelsiska** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#92]
Hi,
When I try to enable the plugin in Blender 2.93.3 on Ubuntu 21.04
I get a traceback error:

`2021-08-21 13:02:22,472 INFO hdusd.init [140556390342912]:  Loading USD Hydra addon version=(1, 0, 21), build=b0bf57e
Traceback (most recent call last):
  File "/snap/blender/539/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/pavel/.config/blender/2.93/scripts/addons/hdusd/__init__.py", line 39, in <module>
    from . import engine, properties, ui, usd_nodes, mx_nodes, bl_nodes
  File "/home/pavel/.config/blender/2.93/scripts/addons/hdusd/engine/__init__.py", line 39, in <module>
    from . import engine, handlers
  File "/home/pavel/.config/blender/2.93/scripts/addons/hdusd/engine/engine.py", line 42, in <module>
    from . import final_engine, viewport_engine, preview_engine
  File "/home/pavel/.config/blender/2.93/scripts/addons/hdusd/engine/final_engine.py", line 25, in <module>
    from ..utils import gl, time_str
  File "/home/pavel/.config/blender/2.93/scripts/addons/hdusd/utils/gl.py", line 29, in <module>
    gl = cdll.LoadLibrary('libGL.so')
  File "/snap/blender/539/2.93/python/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/snap/blender/539/2.93/python/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libGL.so: cannot open shared object file: No such file or directory
`

**Comment by DagerD** [comment]
Hi.

Seems like there is no libGL on your system. You can try to install following packages:
```
libegl-dev (1.3.2-1~ubuntu0.20.04.1)
libgl-dev (1.3.2-1~ubuntu0.20.04.1)
libgl1-mesa-dev (20.2.6-0ubuntu0.20.04.1)
libgles-dev (1.3.2-1~ubuntu0.20.04.1)
libgles1 (1.3.2-1~ubuntu0.20.04.1)
libglvnd-dev (1.3.2-1~ubuntu0.20.04.1)
libglx-dev (1.3.2-1~ubuntu0.20.04.1)
libopengl-dev (1.3.2-1~ubuntu0.20.04.1)
libopengl0 (1.3.2-1~ubuntu0.20.04.1)
```

**Comment by pavelsiska** [comment]
Thanks! It was the libGL like you pointed out. Once I installed the error disappeared.
